# Generated by Django 4.1.2 on 2022-11-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_email_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='piriton.png', null=True, upload_to=''),
        ),
    ]
