# Generated by Django 4.1.2 on 2022-11-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='drug_class',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
