# Generated by Django 4.1.2 on 2022-11-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='piriton.png', null=True, upload_to='uploads/'),
        ),
    ]
