# Generated by Django 4.1.3 on 2022-11-21 13:44

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_dosage_product_form_product_indication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field='image', max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='form',
            field=models.CharField(blank=True, choices=[('tabs', 'Tablet'), ('syrup', 'Syrup'), ('suspension', 'Suspension'), ('injection', 'Injection'), ('capsule', 'Capsule')], default='tabs', max_length=200, null=True),
        ),
    ]
