# Generated by Django 4.1.3 on 2022-11-21 21:44

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=models.ImageField(blank=True, default='sample.png', null=True, upload_to='uploads/'), max_length=18, samples=None),
        ),
    ]
