# Generated by Django 4.1.3 on 2022-11-23 03:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field='image', max_length=18, samples=None),
        ),
    ]
