# Generated by Django 4.1.3 on 2022-11-24 14:47

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field='image', max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='uploads/'),
        ),
    ]
