# Generated by Django 4.1.3 on 2022-11-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='drug_class',
        ),
        migrations.AddField(
            model_name='product',
            name='drug_class',
            field=models.ManyToManyField(to='store.category'),
        ),
    ]
