# Generated by Django 4.1.3 on 2022-11-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_category_remove_product_drug_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='indication',
            field=models.TextField(blank=True, default='ailment', max_length=2000, null=True),
        ),
    ]
