# Generated by Django 4.1.3 on 2022-11-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_product_drug_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(default='nigeria', max_length=200),
        ),
    ]
