# Generated by Django 4.1.3 on 2022-12-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
